# github workflow to publish the /examples folder to the gh-pages branch

name: Pages

on:
  push:
    branches: [$default-branch]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v2
      # we use bun
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Build library
        run: |
          bun install
          bun run build
      - name: Build Examples
        working-directory: examples
        run: |
          bun install
          bun run build
      # publish to gh-pages
      - name: Upload to gh-pages
        uses: actions/upload-artifact@v3
        with:
          path: examples/dist
      - name: Deploy to gh-pages
        uses: actions/deploy-pages@v4
